### ISSUE TITLE
Question about IP Adapter Plus

### ISSUE THREAD

**Issue by danbochman** [tencent-ailab/IP-Adapter#111]
Hi, sorry for another theoretical question... 

In the paper you describe that you're using the penultimate layer of the CLIP image encoder, but in the code it seems like you're using the [layer before the penultimate layer](https://github.com/tencent-ailab/IP-Adapter/blob/main/tutorial_train_plus.py#L403) (at least by my understanding of 'penultimate'). This is also what you're doing in the [inference code](https://github.com/tencent-ailab/IP-Adapter/blob/main/ip_adapter/ip_adapter.py#L246) so I assume it is by design.

They both have shape `[1, 257, 1280]` so wouldn't the last one be even better?

**Comment by xiaohu2015** [comment]
@danbochman hi, the layer refers to the patch feature layer (also is the depth of ViT transformer). For ViT-H, it has 32 layers, hence the penultimate layer is 31 layer.

I think the feature of the penultimate layer and the last layer is very close, hence there won’t be much difference for  generation. As for why we chose this, it is because many text encoders of SD （sd2x and sdxl）currently use the penultimate layer.
